# Generated by Django 4.1.1 on 2022-09-30 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diseasesearch',
            options={'verbose_name_plural': 'DiseaseSearches'},
        ),
    ]
