# Generated by Django 4.1.1 on 2023-01-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_alter_diseasesearch_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseasesearch',
            old_name='search',
            new_name='disease_name',
        ),
        migrations.AddField(
            model_name='diseasesearch',
            name='disease_diet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diseasesearch',
            name='disease_symptoms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
